FORMULA_REFERENCE = {
    "Syntax": {
        "format": "TIMEFRAME/ENTITY: INDICATOR(PARAMETERS) OPERATOR VALUE",
        "example": "60m/Index: SMA(Close,20) > 100",
        "combinators": "Use AND / OR between multiple conditions",
        "example_combo": "60m/Index: RSI(Close,14) < 30 AND 15m/Index: Volume(Volume,10) > 50000",
    },
    "Timeframes": {
        "1m": "1 minute",
        "5m": "5 minutes",
        "15m": "15 minutes",
        "25m": "25 minutes",
        "30m": "30 minutes (expired options only)",
        "60m": "60 minutes (1 hour)",
        "1D": "1 day",
    },
    "Entities": {
        "Index": "Apply indicator on the underlying index (e.g. Nifty 50)",
        "Opt": "Apply indicator on the option instrument itself",
    },
    "Indicators": {
        "SMA(Field, Period)": "Simple Moving Average. Field: Close/High/Low/Open/Volume. Period: number of bars.",
        "EMA(Field, Period)": "Exponential Moving Average.",
        "RSI(Field, Period)": "Relative Strength Index (0-100). Default period 14.",
        "MACD(Field)": "MACD Line value. Uses 12, 26, 9 defaults.",
        "BB(Field, Period)": "Bollinger Bands Middle line. Default period 20, std dev 2.",
        "Supertrend(Field, Period)": "Supertrend direction (1=up, -1=down). Default period 10, mult 3.",
        "ADX(Field, Period)": "Average Directional Index. Default period 14.",
        "ATR(Field, Period)": "Average True Range. Default period 14.",
        "ROC(Field, Period)": "Rate of Change %. Default period 10.",
        "WilliamsR(Field, Period)": "Williams %R (-100 to 0). Default period 14.",
        "StochK(Field, Period)": "Stochastic %K (0-100). Default period 14.",
        "Return(Field, N)": "% return over last N bars. Field: Close.",
        "PositiveCandles(Field, N)": "Count of positive candles (close > open) in last N bars.",
        "NegativeCandles(Field, N)": "Count of negative candles (close < open) in last N bars.",
    },
    "Patterns": {
        "Doji": "Doji candle pattern (small body). Returns True/False.",
        "Engulfing": "Bullish (1) or Bearish (-1) engulfing pattern.",
        "Hammer": "Hammer candlestick pattern (bullish reversal).",
        "ShootingStar": "Shooting star candlestick pattern (bearish reversal).",
    },
    "Special Parameters": {
        "VIX": "Current India VIX value from Yahoo Finance. Usage: VIX > 15",
        "PCR": "Put-Call Ratio of the option chain. Usage: PCR > 1.2",
        "MaxPain": "Distance of spot from Max Pain strike. Usage: MaxPain < 100",
        "IVPercentile": "Current IV rank (0-100) vs historical. Usage: IVPercentile > 50",
        "Delta": "Option Delta (current). Usage: Delta > 0.5",
        "Gamma": "Option Gamma (current). Usage: Gamma < 0.01",
        "Theta": "Option Theta (current). Usage: Theta > -10",
        "Vega": "Option Vega (current). Usage: Vega < 5",
        "BidAskSpread": "Bid-Ask spread of the option. Usage: BidAskSpread < 5",
        "OIChange": "Change in Open Interest of the option. Usage: OIChange > 1000",
        "HourFilter": "Filter trades by market hour. Usage: HourFilter(930,1100)",
        "DayFilter": "Filter trades by weekday. Usage: DayFilter(1,5) for Mon-Fri",
    },
    "Operators": {
        ">": "Greater than",
        "<": "Less than",
        ">=": "Greater than or equal",
        "<=": "Less than or equal",
        "==": "Equal to",
        "!=": "Not equal to",
    },
    "Examples": {
        "Basic SMA": "60m/Index: SMA(Close,20) > 15000",
        "RSI Oversold": "15m/Index: RSI(Close,14) < 30",
        "Volume Spike": "15m/Index: Volume(Volume,10) > 100000",
        "Multi-Condition": "60m/Index: RSI(Close,14) > 50 AND 15m/Index: SMA(Close,20) > SMA(Close,50)",
        "VIX Filter": "VIX > 15 AND 60m/Index: ADX(Close,14) > 25",
        "Pattern Entry": "15m/Index: Engulfing AND 60m/Index: SMA(Close,20) > SMA(Close,50)",
        "Option-Specific": "15m/Opt: Return(Close,5) > 2.5",
        "Premium Decay Filter": "Theta > -15 AND 60m/Index: RSI(Close,14) < 40",
    },
}
